apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - WebAppDB-deployment.yaml
  - storage.yaml
  - configmap.yaml
  - nginx-deployment.yaml
  - service.yaml
  - WebAppDB-deployment.yaml

