apiVersion: apps/v1
kind: Deployment
metadata:
  name: WebApp-nginx
  namespace: WebApp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: WebApp-Nginx
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: WebApp-Nginx
    spec:
      containers:
        - image: nginx:1.27-alpine
          name: nginx-proxy
          ports:
            - containerPort: 80
              protocol: TCP
          volumeMounts:
            - mountPath: /etc/nginx/nginx.conf
              name: WebApp-configmap
              readOnly: true
              subPath: nginx.conf
      restartPolicy: Always
      volumes:
        - configMap:
            items:
              - key: nginx.conf
                path: nginx.conf
            name: WebApp-configmap
          name: WebApp-configmap

