apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: WebApp
spec:
  ports:
    - port: 8080
      targetPort: 80
  selector:
    app: WebApp
  type: ClusterIP

---

apiVersion: v1
kind: Service
metadata:
  name: WebApp
  namespace: WebApp
spec:
  ports:
      port: 5000
      targetPort: 5000
  selector:
    app: WebApp
  type: ClusterIP

