apiVersion: apps/v1
kind: Deployment
metadata:
  name: WebApp
  namespace: WebApp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: WebApp
  template:
    metadata:
      labels: WebApp
    spec:
      containers:
        - env:
            - name: DB_HOST
              value: db
            - name: DB_NAME
              value: appdb
            - name: DB_PASSWORD
              value: secretpassword
            - name: DB_USER
              value: appuser
          image: appoc14/simplewebapp
          name: WebApp
          ports:
            - containerPort: 5000
              protocol: TCP
      restartPolicy: Always

