apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-webapp
  namespace: WebApp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db-webapp
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: db-webapp
    spec:
      containers:
        - env:
            - name: POSTGRES_DB
              value: appdb
            - name: POSTGRES_PASSWORD
              value: secretpassword
            - name: POSTGRES_USER
              value: appuser
          image: postgres:16
          name: webapp-db
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-data
      restartPolicy: Always
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-data

